#!/bin/bash
TMPL=""
TMPL_USERS=""
FRIENDLY_USERS=""
DATA="/usr/local/WEBGOAT_SETUP/internal"

for cat in webgoat_user webgoat_admin admin;
do
	case $cat in
		webgoat_user)
			COUNT=30
			NAME_PREFIX="group"
		;;
		webgoat_admin)
			COUNT=5
			NAME_PREFIX="admin"
		;;
		admin)
			COUNT=5
			NAME_PREFIX="tc-admin"
		;;
	esac


	for i in `seq 1 ${COUNT}`;
	do
		PASSWORD=`pwgen -1 -c -n -s`
		TMPL_USERS="$TMPL_USERS  <user username=\"${NAME_PREFIX}${i}\" password=\"$PASSWORD\" roles=\"$cat\" />\n"
		FRIENDLY_USERS="${FRIENDLY_USERS}${NAME_PREFIX}${i},$PASSWORD\n"
	done
done

#read -r -d '' TMPL << EOF
IFS='' read -r -d '' TMPL << EOF
<?xml version='1.0' encoding='utf-8'?>
<tomcat-users>
  <role rolename="admin" />
  <role rolename="manager" />
  <role rolename="server_admin" />
  <role rolename="webgoat_admin" />
  <role rolename="webgoat_user" />
$TMPL_USERS
</tomcat-users>
EOF

echo -e "$TMPL" > $DATA/tomcat-users.xml
echo -e "$FRIENDLY_USERS" > $DATA/tomcat_users_friendly.csv
echo -e "$TMPL"
echo -e "$FRIENDLY_USERS"
