#!/bin/bash
# 2007-09-16 Chris Dumont
# See "FAI and secrets.txt" for extensive background.
# This script attempts to be idempotent.
#
# 2008-01-04 Updated for new framework.
#
# 2009-10-07 Derek Poon <derekp@ece.ubc.ca>: Abort if rsync fails

# Should probably make this pay attention to classes.

#. /etc/fai/fai.conf

#sleepy() {
#  sleep 161
#}
#trap sleepy ERR

DIRS="/etc/ssh /root/.ssh /var/lib/cfengine2/ppkeys "

SS="/etc/ssh/ssh_host_dsa_key /etc/ssh/ssh_host_rsa_key \
/root/.ssh/id_dsa /root/.ssh/id_rsa /var/lib/cfengine2/ppkeys/localhost.priv"

SSD="/var/lib/cfengine2/ppkeys "

if [ -f /.THIS_IS_THE_FAI_NFSROOT ]; then
  for i in $DIRS ; do
    if ! mount | grep -q " on ${i} type " ; then
      echo "Creating writable ${i}"
      SCRATCH=`mktemp -d`
      rsync -a ${i}/ ${SCRATCH}/ # Trailing slashes are important with rsync.
      mount tmpfs $i -t tmpfs
      rsync -a ${SCRATCH}/ ${i}/
      rm -rf ${SCRATCH}
    fi
  done
fi

for i in $DIRS ; do
  mkdir -p ${i}
  if rsync -a fai@${SERVER}:${FAI_HSEXPORTS}/`hostname`/${i}/ ${i}/ ; then
    echo "Sync'ed ${i}."
  else
    echo "ERROR: Failed to sync ${i}.  No permission to perform FAI?"
    [ "$FAI_ACTION" = install ] && exit 1
  fi
  chown -R root:root ${i}
  find ${i} -type f -exec chmod 644 {} \;
  find ${i} -type d -exec chmod 755 {} \;
  # This must be done immediately otherwise the above rsync will fail on the
  # iteration after doing /root.
  for j in $SS ; do
    [ -f $j ] && chmod 600 $j
  done
  for j in $SSD ; do
    [ -d $j ] && chmod 700 $j
  done
done

# This will skip when called by task_setup (early in the install) but should
# go ahead when called by LAST/40-ssh (late in the install).
#if [ -f /.THIS_IS_THE_FAI_NFSROOT ] && mount | grep -q " on ${target} type " ; then --- Worked for install but not dirinstall
if mount | grep -q " on ${target} type " ; then
  for i in $DIRS ; do
    mkdir -p ${target}/${i}
    rsync -a ${i}/ ${target}/${i}/
  done
fi

# vim: set ts=2 sw=2 et si:
