#!/bin/bash
# 2009-05-27 Chris Dumont. FIXME: Untested so far.

set -e

rm -f $target/root/googleearth*.deb

cat > $target/root/gooscript <<EOF
#!/bin/bash
iam=\`basename \$0\`

[ \`which make-googleearth-package\` ] || exit 1
cd /root
make-googleearth-package --email 'Chris Dumont <chrisd@ece.ubc.ca>' --cleanup --force --quiet
dpkg -i \`ls ./googleearth*.deb | tail -n 1\`
if [ \$? -eq 0 ]; then
    touch /root/\${iam}_success
    rm -f /root/\${iam}_no_success
else
    touch /root/\${iam}_no_success
    rm -f /root/\${iam}_success
fi
rm -rf /root/googleearth*
EOF

chmod +x $target/root/gooscript

$ROOTCMD /root/gooscript
rm -f $target/root/gooscript
