#!/bin/bash

if [ -z "$SERVER" ]; then
	echo "Error: \$SERVER is not set in $0."
	exit 1
fi

# idempotency!
rm -rf $target/opt/Matlab_R2011b/
mkdir -p $target/opt/Matlab_R2011b/

MOUNTPT=/tmp/$SERVER/matlab
mkdir -p "$MOUNTPT"
mount -t nfs -o ro,nolock $SERVER:/exports/matlab "$MOUNTPT"

cd $target/opt/
case `uname -m` in
  i686)
	tar -xzf "$MOUNTPT"/R2011b-i686.tgz
	;;
  x86_64)
	tar -xzf "$MOUNTPT"/R2011b-x86_64.tgz
	;;
  *)
	echo "Don't know my own architecture." >&2
	exit 1
esac

mv /opt/R2011b /opt/Matlab_R2011b # only here because the tarball wasn't built quite right.

umount "$MOUNTPT"

mkdir -p $target/usr/local/bin
cd $target/usr/local/bin
ln -sf /opt/Matlab_R2011b/bin/matlab
ln -sf /opt/Matlab_R2011b/bin/mbuild
ln -sf /opt/Matlab_R2011b/bin/mcc
ln -sf /opt/Matlab_R2011b/bin/mex

