#!/bin/bash
# 2009-01-16 Chris Dumont.
# 2012-06-07 update for R2011b
# fai-server:/srv/fai/config/scripts/OMNI/73-matlab-installer.


if [ "$target" = "" ]; then
  target="/"
fi

# idempotency!
rm -rf $target/opt/Matlab_R2011b/
mkdir -p $target/opt/Matlab_R2011b/

if [ ! -d $target/mnt/huey/exports/ ] || [ ! -r $target/mnt/huey/exports/matlab/r2011b_amd64.bz2 ]; then
	mkdir -p $target/mnt/huey/exports/
	mount -t nfs4 huey:/ $target/mnt/huey/exports
fi

cd $target/opt/
if [ `uname -m` == "i686" ]; then
	tar -xzf $target/mnt/huey/exports/matlab/R2011b-i686.tgz
elif [ `uname -m` == "x86_64" ]; then
	tar -xzf $target/mnt/huey/exports/matlab/R2011b-x86_64.tgz
else
	echo "Don't know my own architecture."
	exit 1
fi

mv /opt/R2011b /opt/Matlab_R2011b # only here because the tarball wasn't built quite right.

umount $target/mnt/huey/exports/

mkdir -p $target/usr/local/bin
cd $target/usr/local/bin
ln -sf /opt/Matlab_R2011b/bin/matlab
ln -sf /opt/Matlab_R2011b/bin/mbuild
ln -sf /opt/Matlab_R2011b/bin/mcc
ln -sf /opt/Matlab_R2011b/bin/mex

