#!/bin/bash

MATLAB_VERSION=R2020a
MATLAB_SOURCE_DIR=sftp://faiclient@filer1.ece.ubc.ca/Matlab
MATLAB_SOURCE_HOST_FINGERPRINT=e29fdd40bf33425d704ea24f7aaa898c

# Idempotency!
if [ -L $target/opt/Matlab_$MATLAB_VERSION ]; then
    ( cd $target/opt
      rm -rf "$(readlink Matlab_$MATLAB_VERSION)"
      mkdir -p "$(readlink Matlab_$MATLAB_VERSION)" )
elif [ -d $target/opt/Matlab_$MATLAB_VERSION ]; then
    rm -rf $target/opt/Matlab_$MATLAB_VERSION
fi


case `uname -m` in
  x86_64)
    mkdir "$target/opt/Matlab_$MATLAB_VERSION"
    # Use curl instead of the OpenSSH SFTP client because it can pipe the output
    curl -o - \
        --key /root/.ssh/id_rsa --pubkey /root/.ssh/id_rsa.pub \
        --hostpubmd5 "$MATLAB_SOURCE_HOST_FINGERPRINT" \
        "$MATLAB_SOURCE_DIR/Matlab_$MATLAB_VERSION.tar.gz" |
    tar xzf - --no-same-owner --strip-components=1 \
        -C "$target/opt/Matlab_$MATLAB_VERSION" ||
    exit 1
    ;;
  i686)
    echo "32-bit Linux is not supported by Mathworks, after 2012." >&2
    exit 1
    ;;
  *)
    echo "Don't know my own architecture." >&2
    exit 1
esac


mkdir -p $target/usr/local/bin
cd $target/usr/local/bin
ln -sf /opt/Matlab_$MATLAB_VERSION/bin/matlab
ln -sf /opt/Matlab_$MATLAB_VERSION/bin/mbuild
ln -sf /opt/Matlab_$MATLAB_VERSION/bin/mcc
ln -sf /opt/Matlab_$MATLAB_VERSION/bin/mex

