#!/bin/bash

if [ -z "$SERVER" ]; then
	echo "Error: \$SERVER is not set in $0."
	exit 1
fi

# Idempotency!
if [ -L $target/opt/Matlab_R2017b ]; then
    ( cd $target/opt
      rm -rf "$(readlink Matlab_R2017b)"
      mkdir -p "$(readlink Matlab_R2017b)" )
elif [ -d $target/opt/Matlab_R2017b ]; then
    rm -rf $target/opt/Matlab_R2017b
fi

MOUNTPT=/tmp/$SERVER/matlab
mkdir -p "$MOUNTPT"
mount -t nfs -o ro,nolock,tcp,rsize=32768 $SERVER:/exports/matlab "$MOUNTPT"

cd $target/opt/
case `uname -m` in
  i686)
	echo "32bit linux is not supported by Mathworks, after 2012." >&2
	exit 1
	;;
  x86_64)
        mkdir Matlab_R2017b &&
	tar -xz --no-same-owner -C Matlab_R2017b --strip-components=1 -f "$MOUNTPT"/Matlab_R2017b.tar.gz
	;;
  *)
	echo "Don't know my own architecture." >&2
	exit 1
esac


umount "$MOUNTPT"

mkdir -p $target/usr/local/bin
cd $target/usr/local/bin
ln -sf /opt/Matlab_R2017b/bin/matlab
ln -sf /opt/Matlab_R2017b/bin/mbuild
ln -sf /opt/Matlab_R2017b/bin/mcc
ln -sf /opt/Matlab_R2017b/bin/mex

