#!/bin/bash

MATLAB_VERSION=R2020a

FILER=filer1.ece.ubc.ca
FILER_SRC_DIR=/data/Linux/Matlab/

# Idempotency!
if [ -L /opt/Matlab_$MATLAB_VERSION ]; then
    ( cd /opt
      rm -rf "$(readlink Matlab_$MATLAB_VERSION)"
      mkdir -p "$(readlink Matlab_$MATLAB_VERSION)" )
elif [ -d /opt/Matlab_$MATLAB_VERSION ]; then
    rm -rf /opt/Matlab_$MATLAB_VERSION
fi


cd /opt/
case `uname -m` in
  i686)
	echo "32bit linux is not supported by Mathworks, after 2012." >&2
	exit 1
	;;
  x86_64)
        mkdir Matlab_$MATLAB_VERSION &&

	ssh -A $FILER "ssh -A $(hostname) <${FILER_SRC_DIR}Matlab_${MATLAB_VERSION}.tar.gz \"tar xzvf - --no-same-owner -C /opt/Matlab_$MATLAB_VERSION --strip-components=1 \""

	;;
  *)
	echo "Don't know my own architecture." >&2
	exit 1
esac


mkdir -p /usr/local/bin
cd /usr/local/bin
ln -sf /opt/Matlab_$MATLAB_VERSION/bin/matlab
ln -sf /opt/Matlab_$MATLAB_VERSION/bin/mbuild
ln -sf /opt/Matlab_$MATLAB_VERSION/bin/mcc
ln -sf /opt/Matlab_$MATLAB_VERSION/bin/mex

