#!/bin/bash

MATLAB_VERSION=R2020a

FILER=filer1.ece.ubc.ca
FILER_SRC_DIR=/data/Linux/Matlab/

# Idempotency!
if [ -L $target/opt/Matlab_$MATLAB_VERSION ]; then
    ( cd $target/opt
      rm -rf "$(readlink Matlab_$MATLAB_VERSION)"
      mkdir -p "$(readlink Matlab_$MATLAB_VERSION)" )
elif [ -d $target/opt/Matlab_$MATLAB_VERSION ]; then
    rm -rf $target/opt/Matlab_$MATLAB_VERSION
fi


cd $target/opt/
case `uname -m` in
  i686)
	echo "32bit linux is not supported by Mathworks, after 2012." >&2
	exit 1
	;;
  x86_64)
        mkdir Matlab_$MATLAB_VERSION &&

	mkfifo scp_pipe

	scp ${FILER}:${FILER_SRC_DIR}Matlab_${MATLAB_VERSION}.tar.gz scp_pipe &

	tar xzf scp_pipe  --no-same-owner -C Matlab_$MATLAB_VERSION --strip-components=1 &&

	rm scp_pipe
	;;
  *)
	echo "Don't know my own architecture." >&2
	exit 1
esac


mkdir -p $target/usr/local/bin
cd $target/usr/local/bin
ln -sf /opt/Matlab_$MATLAB_VERSION/bin/matlab
ln -sf /opt/Matlab_$MATLAB_VERSION/bin/mbuild
ln -sf /opt/Matlab_$MATLAB_VERSION/bin/mcc
ln -sf /opt/Matlab_$MATLAB_VERSION/bin/mex

