#!/bin/bash

if [ -z "$SERVER" ]; then
	echo "Error: \$SERVER is not set in $0."
	exit 1
fi

# idempotency!
rm -rf $target/opt/Matlab_R2013b/
mkdir -p $target/opt/Matlab_R2013b/

MOUNTPT=/tmp/$SERVER/matlab
mkdir -p "$MOUNTPT"
mount -t nfs -o ro,nolock $SERVER:/exports/matlab "$MOUNTPT"

cd $target/opt/
case `uname -m` in
  i686)
	echo "32bit linux is not supported by Mathworks, after 2012." >&2
	exit 1
	;;
  x86_64)
	tar -xzf "$MOUNTPT"/R2013b-x86_64.tgz
	;;
  *)
	echo "Don't know my own architecture." >&2
	exit 1
esac


umount "$MOUNTPT"

mkdir -p $target/usr/local/bin
cd $target/usr/local/bin
ln -sf /opt/Matlab_R2013b/bin/matlab
ln -sf /opt/Matlab_R2013b/bin/mbuild
ln -sf /opt/Matlab_R2013b/bin/mcc
ln -sf /opt/Matlab_R2013b/bin/mex

