#!/bin/bash

if [ -z "$SERVER" ]; then
	echo "Error: \$SERVER is not set in $0."
	exit 1
fi

# idempotency!
rm -rf $target/data/maple12/
mkdir -p $target/usr/local/bin

MOUNTPT=/tmp/$SERVER/exports/maple
mkdir -p "$MOUNTPT"
mount -t nfs -o ro,nolock $SERVER:/exports/maple "$MOUNTPT"

cd $target/
case `uname -m` in
    i686)
	tar -xzf "$MOUNTPT"/Maple12_i386.tgz
	;;
    x86_64)
	tar -xzf "$MOUNTPT"/Maple12_amd64.tgz
	;;
  *)
	echo "Don't know my own architecture." >&2
	exit 1
esac

umount "$MOUNTPT"
