#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

. /usr/lib/fai/subroutines

if ! mountpoint -q $target/boot/efi ; then
    echo "ERROR: /boot/efi is not a mount point"
    exit 1
fi

case "$FAI_ACTION" in
  install)
    if $ROOTCMD which /usr/sbin/grub2-install >/dev/null 2>&1; then
        $ROOTCMD /usr/sbin/grub2-install
    else
        $ROOTCMD /usr/sbin/grub-install
    fi

    if [ $? = 0 ]; then
        echo "Installed GRUB (EFI)"
    else
        echo "ERROR: Failed to install GRUB (EFI)"
    fi
    ;;
esac

exit $error
