#!/bin/bash

### BEGIN INIT INFO
# Provides:          ece_integration
# Required-Start:    $network ntp $time $local_fs $syslog sshd
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Runs cfagent after OS install.
# Description:       Runs cfagent after OS install. Should only 
#                    need to be run once ever in the life of the OS.
### END INIT INFO

[ "$1" = "start" ] || exit 0

echo "Integrating `hostname` into ECE (this will take a while, please be patient). "

# derekp: munin-node's postinst script fails in an FAI environment (some error
# running df).  Workaround.
if [ -x /usr/sbin/munin-node-configure ]; then
    /usr/sbin/munin-node-configure --shell 2> /root/munin-node-configure.log |
        /bin/sh &&
        /etc/init.d/munin-node restart
fi

set -e 

[ -x /usr/sbin/cfagent ] && /usr/sbin/cfagent --no-splay -v -DHourly.Daily.Install | tee /root/cfagent.log.`date +%Y-%m-%d_%H:%M:%S` 

if id monitor >/dev/null 2>/dev/null ; then
    touch /root/runonce_success

    # On Ubuntu, the Upstart configuration will take care of the cleanup
    [ -x /sbin/insserv ] && /sbin/insserv -r runonce

    rm -f /root/runonce_no_success /etc/init.d/runonce
else
    touch /root/runonce_no_success
    echo -n "LDAP accounts not integrated"
    if pgrep -x -f /usr/sbin/nslcd >/dev/null ; then
	    echo " (nslcd is running)."
    else
	    echo " (nslcd is not running)."
    fi
fi
