#!/bin/bash

# For definition of ifclass
. /usr/lib/fai/subroutines

if ! ifclass GNOME && ! ifclass KDE && ! ifclass LXDE && ! ifclass XFCE ; then
	exit 0
fi

if ifclass RPM_BASED ; then
	# Using nvidia-detect from https://elrepo.org/
	recommended=`$ROOTCMD nvidia-detect`
        if [ -n "$recommended" ]; then
		$ROOTCMD yum install -y $recommended $&&
		echo "Installed recommended nVidia driver: $recommended"
	fi

elif ifclass UBUNTU ; then

	# Install the recommended nVidia driver package.
	# Sample output from `ubuntu-drivers devices`:
	#
	# == /sys/devices/pci0000:00/0000:00:02.0/0000:03:00.0 ==
	# vendor   : NVIDIA Corporation
	# model    : GF119 [GeForce GT 610]
	# modalias : pci:v000010DEd0000104Asv00003842sd00002619bc03sc00i00
	# driver   : nvidia-346 - distro non-free recommended
	# driver   : nvidia-304 - distro non-free
	# driver   : nvidia-304-updates - distro non-free
	# driver   : nvidia-340 - distro non-free
	# driver   : xserver-xorg-video-nouveau - distro free builtin
	# driver   : nvidia-340-updates - distro non-free
	# driver   : nvidia-346-updates - distro non-free
	# 
	recommended=`$ROOTCMD ubuntu-drivers devices | awk '
	    $1 == "==" { VENDOR = "" }
	    $1 == "vendor" { $1 = $2 = ""; VENDOR = $0 }
	    $1 == "driver" && VENDOR ~ "NVIDIA" && /recommended/ { print $3 }
	'`
	# Decline to downgrade or remove any existing packages (such as
	# an nvidia-NNN package installed for CUDA).
	if $ROOTCMD apt-get install --no-remove --assume-yes $recommended ; then
		$ROOTCMD update-initramfs -u -k all
		echo "Installed recommended nVidia driver: $recommended"
	else
		echo "Did not install recommended nVidia driver: $recommended"
		exit 1
	fi

fi
