#! /bin/bash

error=0 ; trap "error=$((error|1))" ERR

if [ -e $target/etc/default/grub ]; then
    if ifclass HP_ILO_REV1 ; then
        cat <<-'GRUB_DEFAULTS' >> $target/etc/default/grub
	# cfengine: FAI vvv
	GRUB_CMDLINE_LINUX="console=ttyS0,115200n8r console=tty0 earlycon=uart,io,0x0408,115200n8"
	GRUB_TERMINAL="serial console"
	GRUB_SERIAL_COMMAND="serial --port=0x0408 --speed=115200 --word=8 --parity=no --stop=1"
	GRUB_DISABLE_LINUX_UUID=true
	# cfengine: FAI ^^^
	GRUB_DEFAULTS
    elif ifclass HP_ILO_REV3 ; then
        cat <<-'GRUB_DEFAULTS' >> $target/etc/default/grub
	# cfengine: FAI vvv
	GRUB_CMDLINE_LINUX="console=tty0 console=ttyS1,115200n8r"
	GRUB_TERMINAL="serial console"
	GRUB_SERIAL_COMMAND="serial --unit=1 --speed=115200 --word=8 --parity=no --stop=1"
	GRUB_DISABLE_LINUX_UUID=true
	# cfengine: FAI ^^^
	GRUB_DEFAULTS
    elif ifclass MPT_SCSI ; then
	sed -i 's/\(GRUB_CMDLINE_LINUX=.*\)"/\1 rootdelay=10"/' $target/etc/default/grub
        cat <<-'MPT' >> $target/etc/default/mpt-statusd
	/sbin/modprobe mptctl
	MPT
    elif ifclass AIC79XX ; then
	sed -i 's/\(GRUB_CMDLINE_LINUX=.*\)"/\1 rootdelay=12"/' $target/etc/default/grub
        cat <<-'AIC' >> $target/etc/default/mpt-statusd
	/sbin/modprobe mptctl
	AIC
    fi
fi

exit $error

