#!/bin/bash

patch $target/etc/udev/rules.d/75-persistent-net-generator.rules <<'PATCH'
--- /etc/udev/rules.d/75-persistent-net-generator.rules	2009-08-26 03:27:14.000000000 -0700
+++ ./75-persistent-net-generator.rules	2009-10-26 12:13:03.000000000 -0700
@@ -39,3 +39,11 @@
 # match interface dev_id
-ATTR{dev_id}=="?*", ENV{MATCHDEVID}="$attr{dev_id}"
+#ATTR{dev_id}=="?*", ENV{MATCHDEVID}="$attr{dev_id}"
+# ^^^ Patched by FAI for VM_HOST class ^^^
+# Unlike stock Debian kernels, the pve-kernel-2.6.24-8-pve kernel
+# does not tag network devices with a dev_id.  If udev is first used
+# under a stock Debian kernel, then subsequently under a Proxmox
+# kernel, two sets of rules (with and without considering dev_id)
+# will be generated, leading to inconsistent device naming between
+# Debian and Proxmox kernels.
+ATTR{dev_id}!="0x0", ATTR{dev_id}=="?*", ENV{MATCHDEVID}="$attr{dev_id}"
 
PATCH

sed -i $target/etc/udev/rules.d/70-persistent-net.rules -e '
    s/ATTR{dev_id}=="0x0" *, *//
'
