#! /bin/bash

# echo architecture and OS name in upper case. Do NOT remove these two lines
uname -s | tr '[:lower:]' '[:upper:]'
[ -x "`which dpkg`" ] && dpkg --print-architecture | tr a-z A-Z

[ -f /boot/RUNNING_FROM_FAICD ] && echo "FAICD"

# extract CLASSES given in the kernel FAI_CLASSES parameter passed by
# the loader

if [ -n "$FAI_CLASSES" ]; then
    for class in $(echo $FAI_CLASSES | tr "," "\n"); do
        echo $class
    done
fi

exit 0
