#!/bin/bash

# Detect x86 with 4-64 GiB of RAM, which would benefit from a kernel with PAE
# (Physical Address Extension) support.
if [ "`dpkg --print-architecture`" = i386 ]; then
    if [ `free -g | awk '/^Mem:/ { print $2 }'` -ge 4 ]; then
        echo "I386_BIGMEM"
    fi
fi
