#!/bin/bash

# Inspect output of dmidecode for a stanza with "IPMI" in the name, and
# a non-zero Base Address in the details.
#
# dmidecode can fail.  For example, in OpenVZ containers, it fails with
# "/dev/mem: Operation not permitted".

/usr/sbin/dmidecode -q 2>/dev/null | awk '
    /IPMI/i,/^$/ {
        if (/Base Address:/ && $3 !~ "^0*x*0*$") { print "IPMI" }
    }'
