#! /bin/bash

case $HOSTNAME in
    svpxe[dp]*)
        echo "SERVER FAISERVER" ;;
    svmailp[1-5])
        echo "DHCPC SERVER UBUNTU_MAIL_IMAP" ;;
    smtp?|svsmtpp?)
        echo "DHCPC SERVER MAIL" ;;
    svwebmailp[1-2])
        echo "DHCPC SERVER" ;;
    svsql[dp]*)
        echo "DHCPC SERVER DATABASE RT" ;;
    modigliani)
        # modigliani is not integrated with ECE.
        echo "DHCPC GNOME KDE OMNI" ;;
    [kmx]host*)
        echo "SERVER VM_HOST" ;;
    [kmxv]ldap?|master)
        echo "SERVER LOOKUPSERVER" ;;
    [kmxv]lookup?|svlookup[dp]?)
        case $HOSTNAME in klookup?) echo "RAID" ; esac
        echo "SERVER LOOKUPSERVER" ;;
    msmb1)
        echo "DHCPC SERVER SMBSERVER RAID" ;;
    [kmxv]smb?|svsmbp1)
        echo "DHCPC SERVER SMBSERVER" ;;
    [kmxv]web?|[kmx]vweb?|svweb*)
        echo "DHCPC SERVER WEB RT" ;;
    [kmxv]mx?|[kmx]mail?|*smtp*)
        echo "DHCPC SERVER MAIL WEB" ;;
    [kmxv]flex?)
        echo "DHCPC SERVER" ;;
    node*) # to be clear: these are nodes on Rafeef/morty.
        echo "DHCPC GRID" ;;
    morty)
        echo "DHCPC RAID GRID" ;;
    *webgoat*) 
        echo "DHCPC SERVER WEBGOAT" ;;
    purang1[345])
        echo "DHCPC VM_HOST" ;;
    bci04|mehdi-pc02)
        echo "CUDA" ;;
    *)
        echo "DHCPC" ;;
esac
