#! /bin/bash

echo FAIBASE
echo DHCPC

case $HOSTNAME in
    [kmxv]sql?)
        echo "ECE SERVER WEB DATABASE RT RAID" ;;
    rafiq)
        # rafiq is not integrated with ECE.
        echo "GNOME KDE OMNI " ;;
    lersse1)
        # lersse1 is integrated with ECE but is limited to mounting netapp4:/vol/ECE_vol3/kb/data/backup.
        echo "ECE SERVER GNOME KDE OMNI SLOW " ;;
    modigliani)
        # modigliani is not integrated with ECE.
        echo "ECE_DISK2 GNOME KDE OMNI" ;;
    kakadu|xanadu|[kmx]host*)
        echo "ECE SERVER VM_HOST" ;;
    hooz)
        echo "ECE SERVER VM_HOST RAID" ;;
        # LOOKUPSEVER without ECE only applies packages.
    huey)
        echo "ECE SERVER" ;;
    [kmxv]ldap?|master)
        echo "ECE SERVER LOOKUPSERVER" ;;
    [kmxv]lookup?)
        echo "ECE SERVER LOOKUPSERVER VERTXSERVER" ;;
    msmb1)
        echo "ECE SERVER SMBSERVER RAID " ;;
    [kmxv]smb?)
        echo "ECE SERVER SMBSERVER" ;;
    [kmxv]web1|[kmx]vweb1)
        echo "ECE SERVER WEB RT" ;;
    [kmxv]web?|[kmx]vweb?)
        echo "ECE SERVER WEB" ;;
    [kmxv]mx?|[kmx]mail?)
        echo "ECE SERVER MAIL WEB" ;;
    [kmxv]flex?|vintr1|yoink)
        echo "ECE SERVER " ;;
    mmatlab1|mmatlab2|psserv|ssh-linux[1234]|vb|vklinux[345])
        echo "ECE SERVER GNOME KDE OMNI" ;;
    node*) # to be clear: these are nodes on Rafeef/morty.
        echo "SLOW ECE GRID GNOME KDE OMNI" ;;
    morty)
        echo "SLOW RAID ECE GRID GNOME KDE OMNI" ;;
    scow|thud)
        echo "GNOME NET " ;;
    webgoat) 
        echo "GNOME WEBGOAT" ;;
    bellini|bigboy|blop|cimarosa|morricone|paganini|respighi|vivaldi) 
        echo "" ;;
    nano-mac03)
        echo "ECE ECE_DISK2 GNOME KDE OMNI NOMBR" ;;
    purang1[345])
        echo "ECE VM_HOST GNOME KDE OMNI" ;;
    frink)
        echo "ECE GNOME KDE OMNI " ;;
    ibofh|trirotor)
        echo "ECE GNOME " ;;
    ssh-linux[5678])
        echo "ECE SERVER GNOME KDE OMNI " ;;
    *)
        echo "SLOW ECE GNOME KDE OMNI" ;;
esac
