#! /bin/bash
# 2011-05-19 Chris Dumont. 
# Host *MUST* have two disks. FAI will install to second disk. This is the preferred method.
# For dual-boot on one disk see, for instance, fai/config/disk_config/commlab01

dualboot=$FAI/class/dual-boot

[ -r $dualboot ] || ( echo "ERROR: .../class/dual-boot not readable" ; exec bash -i )

if grep -q "^${HOSTNAME}$" $dualboot ; then
	echo "ECE_DISK2 "
fi
