#!/bin/bash

. /usr/lib/fai/subroutines         # For definition of ifclass

if ifclass RAID || { ifclass SERVER && ifclass VM_GUEST; }; then
    :
elif [ "`/usr/lib/fai-disk-info | wc -l`" != 1 ]; then
    echo "DISK2"
fi
