#! /bin/bash
# 2011-05-10 Chris Dumont. 
# At this time this class is only used for additional packages. This may change
# to include scripts to install, e.g., nvidia differently.

. /usr/lib/fai/subroutines         # For definition of ifclass

if ifclass DEBIAN_6; then
    sqbpolist=$FAI/class/sqbpo

    [ -r $sqbpolist ] || ( "ERROR: .../class/sqbpo not readable" ; exec bash -i )

    if grep -q "^${HOSTNAME}$" $sqbpolist ; then
        echo "SQBPO "
    fi
fi
