#!/bin/bash

. /usr/lib/fai/subroutines

if ! ifclass VZ_CONTAINER ; then
    echo "NOT_VZ_CONTAINER"
    if ! ifclass VM_GUEST ; then
        echo "PHYSICAL"
    fi
fi

for class in STANDARD ECE DHCPC ; do
    if ! ifclass "NO_$class" ; then
        echo "$class"
    fi
done

for class in GNOME LXDE KDE XFCE OMNI ; do
    if ! ifclass "SERVER" && ! ifclass "NO_$class" ; then
        echo "$class"
    fi
done

for class in SLOW ; do
    if [ "$FAI_ACTION" != dirinstall ] && ! ifclass "SERVER" && ! ifclass "NO_$class" ; then
        echo "$class"
    fi
done
