#!/bin/bash

. /usr/lib/fai/subroutines

for class in STANDARD ECE DHCPC ; do
    if ! ifclass "NO_$class" ; then
        echo "$class"
    fi
done

for class in GNOME KDE OMNI ; do
    if ! ifclass "SERVER" && ! ifclass "NO_$class" ; then
        echo "$class"
    fi
done

for class in SLOW ; do
    if [ "$action" != dirinstall ] && ! ifclass "SERVER" && ! ifclass "NO_$class" ; then
        echo "$class"
    fi
done
