#! /bin/bash

# Script to determine the OS classes.

# If an "OS class" is explicitly specified, use that class to define
# the OS to install.  Otherwise, generate OS classes based on the
# NFSroot's OS

# explicit_class(): extract the class that are prefixed by the supported
# OS distributions (currently DEBIAN and UBUNTU)

explicit_class() {
    for class in "$@"; do
	if [[ $class =~ ^(DEBIAN|UBUNTU).* ]]; then
	    echo "$class"
	    return 0
	fi
    done
    return 1
}

# nfsroot_class(): generate the OS classes based on the OS of NFSroot

nfsroot_class() {
    lsb_release -ir 2>/dev/null | awk \
       '/Distributor/ {distribution=toupper($3)}
	/Release/ {release=$2; gsub(/\./, "_", release)}
	END {print distribution "_" release;}'
}

# reduce_versions(): generate new OS class by sequential stripping the _ suffix

reduce_versions() {
    OS="$1"
    case "$OS" in
	*_*)
	    OS="${OS%_*}"
	    echo "$OS"
	    # temporary hack for compatibility
	    [ "$OS" = "DEBIAN_6" ] && echo "SQUEEZE"
	    reduce_versions "$OS"
    esac 
}

# main script

OS=$(explicit_class "$classes")

if [ -z "$OS" ]; then
    OS=$(nfsroot_class)
    echo "$OS"
fi

reduce_versions "$OS" 
