#! /bin/bash

# script to determine the OS classes for this install from the running
# OS of the installation system if there are no predefined OS classes in
# the class list

OSclasses=""

# extract the classes that are prefixed by the supported OS distributions
# (currently DEBIAN and UBUNTU)

for class in ${classes}; do
    if [[ $class =~ ^(DEBIAN|UBUNTU).* ]]; then
	OSclasses="${OSclasses} $class"
    fi
done

# if no OS classes are found generate classes based on the installer OS

if [ -z "$OSclasses" ]; then
    myOS=$(lsb_release -a 2>/dev/null | awk \
	'BEGIN {distribution=""; release=""}
	 /Distributor/ {distribution=toupper($3)}
	 /Release/ {release=$2; gsub(/\./, "_", release)}
	 END {print distribution "_" release}')

    OSclass=""
    for word in $(echo $myOS | tr "_" "\n"); do
	if [ -z "${OSclass}" ]; then
	    OSclass="${word}"
	else
	    OSclass="${OSclass}_${word}"
	fi
	echo "${OSclass}"
    done
fi

# whilst testing add the original Debian stable release

echo "SQUEEZE"

exit 0
