#!/bin/bash

[ "$do_init_tasks" = 1 ] || exit 0 # Only continue when doing install (not a dirinstall)

. /usr/lib/fai/subroutines         # For definition of ifclass

disk_sizes() {
	# Output the size of each disk, in kiB, in the natural enumeration order
	/usr/lib/fai/fai-disk-info | while read dev ; do
		awk -v dev="$dev" '$4 == dev { print $3 }' /proc/partitions
	done
}

disk_count() {
	/usr/lib/fai/fai-disk-info | wc -l
}

if ifclass RAID1 ; then
	exit

elif ifclass DISK1P3 ; then
	exit

elif ifclass VMWARE_GUEST ; then
	if [ `disk_count` = 1 ]; then
		ifclass VM_GUEST || echo "VM_GUEST"
	else
		echo "VM_GUEST2"
	fi

elif ifclass VM_HOST ; then
	# FIXME: It would be nice if all servers could use a common layout and this line could go away.
	exit 0

elif [ `disk_count` -gt 2 ]; then
	die "Too many hard disks. Too risky."

elif ifclass DISK2 ; then
	size=`disk_sizes | tail -n 1`
	if   [ "$size" -lt  40000000 ]; then die "The hard disk is too small (40 GB minimum)."
	elif [ "$size" -lt 100000000 ]; then echo "MEDIUM2"
	else                                 echo "LARGE2"
	fi

else
	size=`disk_sizes | head -n 1`
	if   [ "$size" -lt  10000000 ]; then die "The hard disk is too small (10 GB minimum)."
	elif [ "$size" -lt  40000000 ]; then echo "SMALL"
	elif [ "$size" -lt 100000000 ]; then echo "MEDIUM"
	elif ifclass RAID             ; then echo "RAID1"
	else                                 echo "LARGE"
	fi
fi
