#!/bin/bash

[ "$do_init_tasks" = 1 ] || exit 0 # Only continue when doing install (not a dirinstall)

. /usr/lib/fai/subroutines         # For definition of ifclass

disk_sizes() {
	# Output the size of each disk, in kiB, in the natural enumeration order
	/usr/lib/fai/fai-disk-info | while read dev ; do
		awk -v dev="$dev" '$4 == dev { print $3 }' /proc/partitions
	done
}

disk_count() {
	/usr/lib/fai/fai-disk-info | wc -l
}

if ifclass SERVER && ifclass VMWARE_GUEST ; then
	[ `disk_count` = 1 ] && echo "VIRTS" || echo "VIRTS2"

elif ifclass SERVER ; then
	# FIXME: It would be nice if all servers could use a common layout and this line could go away.
	ifclass VM_HOST && exit 0

	# On SERVERs, assume that we want to install to the first disk.
	size=`disk_sizes | head -n 1`

	if   [ "$size" -lt  10000000 ]; then die "The hard disk is too small (10 GB minimum)."
	elif [ "$size" -lt  35000000 ]; then echo "TINYS"
	elif [ "$size" -lt  70000000 ]; then ifclass RAID && echo "RAID1SS" || echo "SMALLS"
	elif [ "$size" -lt 500000000 ]; then ifclass RAID && echo "RAID1MS" || echo "MEDIUMS"
	else                                 echo "HUGE"
	fi

elif [ `disk_count` -gt 2 ]; then
	die "Too many hard disks. Too risky."

else
	# On non-SERVERs, assume that we want to install to the last disk.
	size=`disk_sizes | tail -n 1`

	if   [ "$size" -lt  10000000 ]; then die "The hard disk is too small (10 GB minimum)."
	elif [ "$size" -lt  35000000 ]; then echo "TINYW"
	elif [ "$size" -lt  70000000 ]; then ifclass ECE_DISK2 && echo "SMALLW2"  || echo "SMALLW"
	elif [ "$size" -lt 500000000 ]; then ifclass ECE_DISK2 && echo "MEDIUMW2" || echo "MEDIUMW"
	else                                 ifclass ECE_DISK2 && echo "HUGE2"    || echo "HUGE"
	fi
fi
