#!/bin/sh
# Add classes for special hardware.

handle_device() {
    progif=
    rev=
    for var in slot class vendor device subsystem_vendor subsystem_device ; do
        while true ; do
            val="$1" ; shift
            case "$val" in
              -p*) progif="$val" ;;
              -r*) rev="$val"    ;;
              -*)  ;;
              *)   declare $var="$val" ; break ;;
            esac
        done
    done

    case "$vendor:$device" in
      'Compaq Computer Corporation:Integrated Lights Out Controller'|\
      'Hewlett-Packard Company:iLO3 Management Processor Support and Messaging')
        case "$rev" in
          '-r01')   echo 'HP_ILO HP_ILO_REV1' ;;
          '-r03')   echo 'HP_ILO HP_ILO_REV3' ;;
          '-r04')   echo 'HP_ILO HP_ILO_REV4' ;;
        esac
        ;;
      'LSI Logic / Symbios Logic:53c1030 PCI-X Fusion-MPT'*)
        case "$subsystem_vendor" in
          'VMware') : ;;
          *)        echo 'MPT_SCSI' ;;
        esac
        ;;
      'Adaptec:AIC-79'*)
        echo 'AIC79XX'
        ;;
    esac
}

lspci -mm | while read line ; do
    eval "handle_device $line"
done
