#!/bin/bash
# 2007-11-09 Chris Dumont. Set up a comfy gnome desktop for root.

cd $target/root
if [ -d .gnome/ ] ; then
	echo "$0: Not overwriting existing .gnome and friends."
	exit 0
fi
tar -xzf $FAI/scripts/GNOME/root_home.tgz

