#!/bin/bash
# 2008-12-18 Chris Dumont
# Do we have an ATI card? Uninstall nvidia stuff and replace with ati stuff.
#set -x

$ROOTCMD update-pciids >/dev/null 2>/dev/null

HAS_ATI=`$ROOTCMD lspci | grep VGA | grep ATI`
if [ -z $HAS_ATI ]; then
	exit 0
fi

set +x
fcopy -iBM /etc/X11/xorg.conf
