#!/bin/bash

# This runs to completion when in network boot (FAI install?) mode. Creates
# script to run on first local disk boot which, during successful execution,
# erases itself.

fcopy -B /etc/init.d/runonce

if [ -x $target/sbin/insserv ]; then
    # Debian has /sbin/insserv
    $ROOTCMD /sbin/insserv -d runonce

elif [ -d $target/etc/init ]; then
    # Compatibility hook to run /etc/init.d/runonce on systems that use Upstart
    fcopy -iB /etc/init/runonce.conf

fi
