#!/bin/bash
# Chris Dumont 2007-11-14. 2010-01-21 squeeze update. 2010-02-24 Add LSB Info.

# This runs to completion when in network boot (FAI install?) mode. Creates
# script to run on first local disk boot which, during successful execution,
# erases itself.

fcopy -B /etc/init.d/runonce
$ROOTCMD /sbin/insserv -d runonce

