#!/bin/sh

if [ -x "$target/usr/bin/puppet" ]; then
    PUPPET_OPTS=--verbose
    if [ -n "$PUPPET_SERVER" ]; then
        PUPPET_OPTS="$PUPPET_OPTS --server $PUPPET_SERVER"
    fi
    $ROOTCMD /usr/bin/puppet agent --test --waitforcert 60 $PUPPET_OPTS
fi
