#!/bin/sh

( cd $NFSROOT && patch -p0 ) <<'PATCH'
The Linux::LVM Perl package introduced a compatibility bug while attempting to
address https://rt.cpan.org/Public/Bug/Display.html?id=94991 .  When calling
Linux::LVM::get_vg_information() with lvm2 < 2.02.89, the LV Name of nearly
every logical volume is ignored.

This could have serious consequences in fai-setup-storage, such as attempting
to destroy the wrong volume.
--- usr/share/perl5/Linux/LVM.pm.cpan94991	2014-06-27 16:25:59.000000000 +0000
+++ usr/share/perl5/Linux/LVM.pm	2015-06-19 16:38:58.000000000 -0700
@@ -290,6 +290,6 @@
 
         # Parse the logical volume name.
-        elsif( m/LV Name\s+(\S+)/ ) { 
-            $lvn = $1 unless $lvn;
+        elsif( m/LV Name\s+(\S+\/\S+)/ ) { 
+            $lvn = $1;
             $vghash{$vgn}->{lvols}->{$lvn}->{name} = $1; 
             next VGINF; }
@@ -297,5 +297,5 @@
         # since version 2.02.89 'LV Name' is no longer the full path, 'LV Path' is.
         # LV Path may be bogus or missing in some cases, such as thin pools.
-        if( m/LV Path\s+(\S+)/ ) {
+        elsif( m/LV Path\s+(\S+)/ ) {
             $lvn = $1;
             $vghash{$vgn}->{lvols}->{$lvn}->{name} = $1;
