#!/bin/sh

( cd $NFSROOT && patch -p0 ) <<'PATCH'
--- fai-setup-storage-4.2/bin/setup-storage
+++ usr/sbin/setup-storage
@@ -237,14 +237,15 @@ foreach (&numsort(keys %FAI::commands)) {
 
 # generate the proposed fstab contents
 # wait for udev to set up all devices
-`$FAI::udev_settle`;
-my @fstab = &FAI::generate_fstab(\%FAI::configs);
+if ($FAI::no_dry_run) {
+  `$FAI::udev_settle`;
+  my @fstab = &FAI::generate_fstab(\%FAI::configs);
 
-# print fstab
-$FAI::debug and print "$_\n" foreach (@fstab);
+  # print fstab
+  $FAI::debug and print "$_\n" foreach (@fstab);
 
-# write the proposed contents of fstab to $FAI::DATADIR/fstab
-if ($FAI::no_dry_run) {
+
+  # write the proposed contents of fstab to $FAI::DATADIR/fstab
   open(FSTAB, ">$FAI::DATADIR/fstab")
     or die "Failed to open $FAI::DATADIR/fstab for writing\n";
   print FSTAB "$_\n" foreach (@fstab);
PATCH
